databases:
  - name: portfolio
    plan: free
    ipAllowList: []
    # databaseName: what-about
    # user: what-about

services:
  - type: web
    name: laurene-epp
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: cache
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu