databases:
  - name: portfolio
    plan: free
    ipAllowList: []

services:
  - type: web
    name: laurene-epp
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: cache
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu